const mock = {
    data: {
        total: 42,
        list: [
            {
                id: 1,
                lat: -23.55052,
                lng: -46.633308,
                locationLabel: "São Paulo, São Paulo, Brasil",
                fidelityFree: false,
                velocity: 100,
                technology: "fibra",
                installationFree: true,
                resultsCount: 3,
                uidUser: null,
                createdAt: "2025-02-10T14:32:00.000Z",
            },
            {
                id: 2,
                lat: -22.906847,
                lng: -43.172897,
                locationLabel: "Rio de Janeiro, Rio de Janeiro, Brasil",
                fidelityFree: true,
                velocity: 200,
                technology: "fibra",
                installationFree: false,
                resultsCount: 5,
                uidUser: "user-abc-123",
                createdAt: "2025-02-10T13:15:00.000Z",
            },
            {
                id: 3,
                lat: null,
                lng: null,
                locationLabel: null,
                fidelityFree: false,
                velocity: null,
                technology: null,
                installationFree: true,
                resultsCount: 0,
                uidUser: null,
                createdAt: "2025-02-09T18:00:00.000Z",
            },
            {
                id: 4,
                lat: -19.916681,
                lng: -43.934493,
                locationLabel: "Belo Horizonte, Minas Gerais, Brasil",
                fidelityFree: true,
                velocity: 300,
                technology: "cabo",
                installationFree: true,
                resultsCount: 8,
                uidUser: null,
                createdAt: "2025-02-09T12:45:00.000Z",
            },
            {
                id: 5,
                lat: -25.428954,
                lng: -49.271934,
                locationLabel: "Curitiba, Paraná, Brasil",
                fidelityFree: false,
                velocity: 100,
                technology: "fibra",
                installationFree: false,
                resultsCount: 2,
                uidUser: "user-xyz-456",
                createdAt: "2025-02-08T09:20:00.000Z",
            },
        ],
    },
};

export default mock;
